Fixing shader by not moving the vertex in isometric mode
Unity-Technologies/com.unity.probuilder pull request #346
Opened 2020-10-26 15:59 UTC by lopezt-unity

### Purpose of this PR

In Isometric mode vertex only have X and Y taken into account:
x = width, y = height (z is unused)

The position of the vertex is not moved when using isometric mode.
The rendering is ok, and no depth conflicts arise.

Before :
![image](https://user-images.githubusercontent.com/66317117/97196187-7a622c00-17ac-11eb-92c2-0ec8fddd2fc7.png)

After : 👍 
![image](https://user-images.githubusercontent.com/66317117/97196282-949c0a00-17ac-11eb-8743-62a6f622599c.png)

### Links

**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1285654/

### Comments to Reviewers

Maybe we can use the same simplest approach for perspective camera as it doesn't seem to create depth ordering conflicts.

2020-10-30 15:16 UTC, JoelFortin approved these changes
Peer-reviewed with Thomas. Approving

2020-10-30 21:33 UTC, karl- requested changes

2020-12-23 14:22 UTC, lopezt-unity commented on Content/Shader/FaceHighlight.shader
> +                o.pos = o.pos * (1.0f - unity_OrthoParams.w) + UnityObjectToClipPos(v.vertex.xyz) * unity_OrthoParams.w;
@karl- , I did some tests and need your input on this...

It seems that this code is creating z-fighting:
```
                float3 viewPos = mul(UNITY_MATRIX_MV, float4(v.vertex.xyz, 1.0)).xyz;
                o.pos = mul(UNITY_MATRIX_P, float4(viewPos, 1.0));
```
Here : 
![shader-zfight](https://user-images.githubusercontent.com/66317117/103005042-1fda1780-4532-11eb-8e32-37ebd112b257.gif)

While this (simple!!! :o ) one is not:
`o.pos = UnityObjectToClipPos(v.vertex.xyz);`

Here with isometric and perspective views:
![shader-no-zfight](https://user-images.githubusercontent.com/66317117/103006622-8d864380-4532-11eb-8750-58d208d01598.gif)

So we could simplify the vert shader to use this only...

2020-12-23 14:26 UTC, lopezt-unity commented on Content/Shader/FaceHighlight.shader
> +                o.pos = o.pos * (1.0f - unity_OrthoParams.w) + UnityObjectToClipPos(v.vertex.xyz) * unity_OrthoParams.w;
It's working on windows (DX11, OpenGL ES 3 and OpenGL Core), Unity 2019.4.
Could you try by any chance on MacOS?

2021-01-22 17:43 UTC, karl- approved these changes

2021-01-27 08:25 UTC, merged