Fixed warning when modifying a PBMesh with particule effect using PBMesh as shape emitter
Unity-Technologies/com.unity.probuilder pull request #347
Opened 2020-10-27 14:15 UTC by lopezt-unity

### Purpose of this PR

Fixed warning when modifying a PBMesh with particule effect using PBMesh as shape emitter.
Mesh.Optimize was causing the mesh the be cleaned even when no vertices has been changed, causing the warning message.

### Links

**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1281658/
**Jira:**

### Comments to Reviewers

[List known issues, planned work, provide any extra context for your code.]

2020-10-30 15:30 UTC, JoelFortin requested changes
If the emitter's topology is modified while emitting particules ... we'll still get the warning in the console.

2020-11-16 14:57 UTC, karl- approved these changes

2021-01-22 13:34 UTC, lopezt-unity commented
> If the emitter's topology is modified while emitting particules ... we'll still get the warning in the console.

This is now handled, no warning message should be triggered by the particle system

2021-01-26 18:07 UTC, JoelFortin approved these changes
LGTM

2021-01-27 08:18 UTC, merged