Analytics initial implementation
Unity-Technologies/com.unity.probuilder pull request #358
Opened 2020-12-03 05:50 UTC by JoelFortin

Initial Implementation for ProBuilder Analytics:
- Each actions are now registering analytics when triggered.
- For now, only the action triggers are send to the database

Here's the format that will be sent for action registration:
- Action Name
- ActionType Name
- Active SubLevel
- Active SubLevel Id
- From where is was triggered (UI or Menus(also including shortcuts))

2020-12-03 05:58 UTC, JoelFortin commented
While testing ... I noticed that only the menu entry for Poly Shape triggers the analytics, the button from the PB window doesn't.
I'll your help to figure this out.

2020-12-03 14:46 UTC, karl- requested changes

2020-12-03 14:46 UTC, karl- commented on Editor/EditorCore/ProBuilderAnalytics.cs
> +                Console.WriteLine("[PB] Editor analytics are disabled");
remove debug logs

2020-12-03 14:46 UTC, karl- commented on Editor/EditorCore/ProBuilderAnalytics.cs
> +        private static bool RegisterEvents()
style guide - omit redundant access modifiers. ex, `static bool RegisterEvents()` because `private` is implicit.

2020-12-03 14:46 UTC, karl- commented on Editor/EditorCore/ProBuilderAnalytics.cs
> +        private static void Send(EventName eventName, object eventData)
style - omit `private`

2020-12-03 14:46 UTC, karl- commented on Editor/EditorCore/ProBuilderAnalytics.cs
> +                Console.WriteLine($"[PB] Analytics deactivated, ProBuilder is currently used in Batch mode or run by automated system.");
remove debug logs, or enclose in the `PB_ANALYTICS_LOGGING` define

2020-12-03 14:46 UTC, karl- commented on Editor/EditorCore/ProBuilderAnalytics.cs
> +                Console.WriteLine($"[PB] Analytics deactivated, Dev build of ProBuilder is currently used.");
remove debug logs, or enclose in the PB_ANALYTICS_LOGGING define

2020-12-03 14:46 UTC, karl- commented on Editor/EditorCore/ProBuilderAnalytics.cs
> +            probuilderAction
style guide - enum values should be `PascalCase`

2020-12-04 14:35 UTC, lopezt-unity commented
I added Analytics in the Menu toggles as well

2020-12-16 14:07 UTC, karl- approved these changes

2021-03-02 15:18 UTC, karl- commented on Editor/EditorCore/ProBuilderAnalytics.cs
> +#define PB_ANALYTICS_ALLOW_DEVBUILD
Should this be enabled?

2021-03-08 02:34 UTC, merged