Fixing PBShape export using FBX Exporter
Unity-Technologies/com.unity.probuilder pull request #394
Opened 2021-05-19 19:51 UTC by lopezt-unity

### Purpose of this PR

Fixing Probuilder mesh throwing errors with FBX Exporter due to the presence of ProBuilderShape that was not removed.
The PR calls the `StripProBuilderScripts` class now for more consistency and the code is now also aware of the difference between "FBX Export" that does not replace the PB Object and "Convert to prefab" that creates a prefab, strips PB objects and replace the object in the scene.

![FBXexportResolution](https://user-images.githubusercontent.com/66317117/118875396-027b6080-b8ba-11eb-8e5a-3803f11eb4af.gif)

### Links

**Fogbugz:** https://fogbugz.unity3d.com/f/cases/1334017/

### Comments to Reviewers

[List known issues, planned work, provide any extra context for your code.]

2021-05-19 20:03 UTC, karl- requested changes

2021-05-19 20:03 UTC, karl- commented on Addons/Fbx.cs
>                 .First(t => t.ContainsGenericParameters);
We should replace the reflection here with an optional dependency on FBX Exporter

2021-05-19 20:03 UTC, karl- commented on Addons/Fbx.cs
> +                StripProBuilderScripts.DoStrip(pmesh);
nice 🥇

2021-05-19 21:57 UTC, karl- approved these changes

2021-06-02 15:29 UTC, JoelFortin approved these changes
LGTM. Tried Export and Convert.
Also note for @vkovec, the warning we get about the temp meta file that needs to be deleted is logged right ?

2021-06-08 17:37 UTC, vkovec commented
@JoelFortin Yes I don't think the warning was specific to Probuilder, we have made a fix for the next release

2021-06-08 17:37 UTC, vkovec approved these changes

2021-06-08 18:36 UTC, merged