[PBLD-129] Fixing redo problem with PB Actions
Unity-Technologies/com.unity.probuilder pull request #514
Opened 2024-06-03 17:10 UTC by lopezt-unity

### Purpose of this PR

Removing a NonVersionedEditScope.
This was introduced when the Mesh Version index was not serialized. Now this value is serialized, we need that for the Undo and Redo to work properly.

### Links

**Jira:** https://jira.unity3d.com/browse/PBLD-128

### Comments to Reviewers

[List known issues, planned work, provide any extra context for your code.]

2024-06-03 17:10 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.probuilder?pullRequest=514) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.probuilder?pullRequest=514) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.probuilder?pullRequest=514) it.</sub>

2024-06-06 20:45 UTC, claudiaantoun approved these changes

2024-06-11 18:06 UTC, modrimkus-unity requested changes
May I request a test here? Seems a critical part, would not be great to break it again later. Looks good otherwise.

2024-06-21 17:26 UTC, modrimkus-unity approved these changes

2024-06-21 17:41 UTC, merged